refactor: Remove npm, yarn based lock files from client dockerfile, resolved TODOs

diff --git a/client/Dockerfile b/client/Dockerfile
--- a/client/Dockerfile
+++ b/client/Dockerfile
@@ -8,17 +8,14 @@ FROM base AS deps
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-# Stage 2: Create the final image
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
 RUN \
-    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-    elif [ -f package-lock.json ]; then npm ci; \
-    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
-    else echo "Lockfile not found." && exit 1; \
+    if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+    else echo "PNPM Lockfile not found." && exit 1; \
     fi
 
 
-#! Stage 1: Create the final application image.
+#! Stage 2: Build the application image.
 FROM base AS builder
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
@@ -28,13 +25,11 @@ COPY . .
 ENV NEXT_TELEMETRY_DISABLED=1
 
 RUN \
-    if [ -f yarn.lock ]; then yarn run build; \
-    elif [ -f package-lock.json ]; then npm run build; \
-    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-    else echo "Lockfile not found." && exit 1; \
+    if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+    else echo "PNPM Lockfile not found." && exit 1; \
     fi
 
-# Production image, copy all the files and run next
+#! Stage 3: Runner: Create final application image.
 FROM base AS runner
 WORKDIR /app
 
